name: Backend CI

on:
    push:
        branches:
            - main
        paths:
            - "backend/**.js"

    workflow_dispatch:
    
env:
  TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
  PORT: ${{ secrets.PORT }}
  SECRET: ${{ secrets.SECRET }}

jobs:
    continuous_integration:
        runs-on: ubuntu-20.04
        defaults:
            run:
                working-directory: backend
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: "16.13.0"
            - name: Install dependencies
              run: npm ci
            - name: Check style
              run: npm run lint
            - name: Unit tests
              run: npm run test
