name: Deploy to Fly.io

on:
  workflow_run:
    workflows: ["Frontend CI", "Backend CI", "End to end tests"]
    types:
      - completed
      
  workflow_dispatch:
      
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Cancel deployment if a preceding workflow failed
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        run: exit 78
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Configure .env file
        run: echo "TEST_MONGODB_URI=${{ secrets.TEST_MONGODB_URI }}" >> .env && echo "SECRET=${{ secrets.SECRET }}" >> .env
        working-directory: backend
      - name: Deploy
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
