name: Frontend CI

on:
    push:
        branches:
            - main
        paths:
            - "frontend/**.js"

    workflow_dispatch:

jobs:
    continuous_integration:
        runs-on: ubuntu-20.04
        defaults:
            run:
                working-directory: frontend
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: "16.13.0"
            - name: Install dependencies
              run: npm ci
            - name: Check style
              run: npm run lint
            - name: Build
              run: npm run build
            - name: Unit tests
              run: npm run test:nowatch
                
                
