name: Frontend CI

on:
    push:
        branches:
            - main
        paths:
            - "frontend/**.js"

    workflow_dispatch:
    
env:
  TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
  PORT: ${{ secrets.PORT }}
  SECRET: ${{ secrets.SECRET }}

jobs:
    continuous_integration:
        runs-on: ubuntu-20.04
        defaults:
            run:
                working-directory: frontend
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: "16.13.0"
                  cache: "npm"
                  cache-dependency-path: "frontend/package-lock.json"
            - name: Install dependencies
              run: npm ci
            - name: Check style
              run: npm run lint
            - name: Build
              run: npm run build
            - name: Unit tests
              run: npm run test:nowatch
            - name: Install backend dependencies for end to end tests
              run: npm ci
              working-directory: backend
            - name: Start backend
              run: npm run start:test &
              working-directory: backend  
            - name: Run end to end tests
              uses: cypress-io/github-action@v5
              with:
                command: npm run cypress:e2e
                start: npm start
                wait-on: "http://localhost:3000, http://localhost:3003"
                working-directory: frontend
                
                
